name: Other
description: Can't find the right issue type? Use this one!
title: "[MISC] <title>"
labels: ["type: other"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if a similar issue already exists
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Please provide a description for this request
    validations:
      required: true