name: Question
description: Ask the Trust0 developers
title: "[QUESTION] <title>"
labels: ["type: question"]
body:
  - type: markdown
    attributes:
      value: |
        Please keep in mind that this issue tracker should be used for reporting bugs or proposing improvements to the Trust0 framework.
  
        It is also possible that your question was already asked here, so please do a quick issues search before submitting.
  
        That said, please feel free ask your question :)
  - type: checkboxes
    attributes:
      label: Is there a similar existing question?
      description: Please search to see if a similar question already exists
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Question
      description: Please provide your question
    validations:
      required: true
